name: Build macOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build App
      # CHANGE "main.py" BELOW TO YOUR ACTUAL FILE NAME IF IT IS DIFFERENT
      run: |
        pyinstaller --onefile --windowed XJT.py 

    - name: Upload Finished App
      uses: actions/upload-artifact@v4
      with:
        name: My-Mac-App
        path: dist/
